apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: log_system
    user: root
    secureJsonData:
      password: ##enterpassword
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
